services:
  postgresql:
    image: bitnami/postgresql:11
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      ALLOW_EMPTY_PASSWORD: "yes"
      POSTGRESQL_USERNAME: keycloak
      POSTGRESQL_DATABASE: keycloak
  keycloak:
    image: bitnami/keycloak:24.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgresql
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_EXTRA_ARGS: "--import-realm"
    volumes:
      - ./keycloak/realms:/opt/bitnami/keycloak/data/import
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
