package com.sprylab.purple.example.model

enum class EntitlementErrorCode {
    UNKNOWN,
    WRONG_PASSWORD_OR_USERNAME,
    USER_DEACTIVATED,
    AUTHENTICATION_ERROR,
    WRONG_PASSWORD,
    INSTALLATION_LIMIT_EXCEEDED,
    SYSTEM_ERROR_IN_REMOTE_SYSTEM,
    PARAMETER_ERROR_IN_REMOTE_SYSTEM
}
